---
- hosts: nodes

  become: true

  tasks:
    - name: Install li.nux.ro repos
      yum:
        name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
        state: latest
        update_cache: yes
