---
- hosts: nodes

  become: true

  tasks:
    - name: Install PostgreSQL
      yum:
        name: 
          - postgresql-server
          - postgresql-contrib
          - postgresql-devel
        state: latest
        update_cache: yes

    - name: Initialize PostgreSQL
      shell: postgresql-setup initdb

    - name: Enable and start PostgreSQL
      systemd:
        state: started
        enabled: yes
        name: postgresql

    - name: Recreate template1 with UTF-8 charset
      shell: |
        psql -c "UPDATE pg_database SET datistemplate = FALSE WHERE datname = 'template1';"
        psql -c 'DROP DATABASE template1;'
        psql -c "CREATE DATABASE template1 WITH TEMPLATE = template0 ENCODING = 'UNICODE';"
        psql -c "UPDATE pg_database SET datistemplate = TRUE WHERE datname = 'template1';"
      become: yes
      become_user: postgres

    - name: VACUUM FREEZE template1 database
      command: psql -d template1 -c "VACUUM FREEZE;"
      become: yes
      become_user: postgres
