---
- hosts: nodes

  become: true

  tasks:
    - name: Update System (RHEL-based)
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"
    
    - name: Update System (Debian-based)
      apt:
        upgrade: yes
        update_cache: yes
      when: ansible_os_family == "Debian"